### ISSUE TITLE
Use z-distribution for GLMs with dispersion parameter fixed to 1

### ISSUE THREAD

**Issue by matthewravery** [jthaman/ciTools#13]
At present, many GLM methods use t-distributions rather than z-distributions for GLMs where the dispersion parameter is fixed at 1. (See Section 2.6.2 of Applied generalized linear mixed models: Continuous and discrete data, 2010.) These methods should use a standard normal instead. See add_ci.glm, add_pi.glm, etc.

**Comment by jthaman** [comment]
atm add_pi.glm is doing a simulation via arm::sim, but I will keep this in mind when I try to write a parametric solution for GLM PIs.

**Comment by jthaman** [comment]
Note to remind myself to make a list of GLMs with dispersion param = 1.

**Comment by jthaman** [comment]
I looked in the code of `summary.glm` and found that you are correct: poisson and binomial GLMs are the only families where the dispersion param is set to one.
