### ISSUE TITLE
Equations in vignettes isn't rendering properly in RStudio

### ISSUE THREAD

**Issue by matthewravery** [jthaman/ciTools#23]
When viewed through the help file interface in RStudio, the equations don't render properly. They seem fine when accessed from the CRAN or other external sites, so I'm not sure what the problem is. Can you double-check this and let me know if it's only a problem on my end?

**Comment by jthaman** [comment]
I checked and am also having this problem. I'm not sure if this is an issue with ciTools or Rstudio -- Maybe the Rstudio browser cannot render MathJax equations in vignettes. If it's a problem with ciTools, have you seen another html vignette render equations successfully in the Rstudio browser?

**Comment by jthaman** [comment]
Hi, I asked about this on the Rstudio issue tracker https://github.com/rstudio/rstudio/issues/2253

**Comment by jthaman** [comment]
There's nothing we can do about this, it's a bug in Rstudio that affects different versions on different platforms. https://github.com/rstudio/rstudio/issues/2253#issuecomment-368020060
