### ISSUE TITLE
Literature review

### ISSUE THREAD

**Issue by TimTaylor** [jthaman/ciTools#47]
Is this literature review mentioned in these [slides](https://www.ida.org/-/media/feature/publications/i/in/introduction-to-citools/d-8702.ashx) publicly available anywhere?

**Comment by jthaman** [comment]
Hi Tim, the literature review is not released, it's partially contained in the vignettes of the package. I might be able to answer some specific questions though

**Comment by TimTaylor** [comment]
Cheers John.  I'll work through the vignettes and will let you know if I have any specific questions.
